# Generated by Django 6.1 on 2026-08-07 13:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_description_venue_rental_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='venue_photo'),
        ),
    ]
