# Generated by Django 6.1 on 2026-08-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_needs_venue_tournament_venue_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
