# Generated by Django 6.1 on 2026-08-08 19:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='organization_logo')),
                ('landing_video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='landing_background_video')),
                ('login_background', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='login_background')),
                ('register_background', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='register_background')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
